In [7]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", 50)
RANDOM_STATE = 42

## 1. Load data

In [3]:
DATA_PATH = "./data/market_bars_30m_with_backfill.csv"

raw = pd.read_csv(DATA_PATH, parse_dates=["bar_open_time_utc"])
raw = raw.sort_values("bar_open_time_utc").reset_index(drop=True)

df = raw[["bar_open_time_utc", "open", "high", "low", "close", "volume", "quote_volume", "trade_count"]].copy()
df = df.set_index("bar_open_time_utc")

print(df.shape)
print(df.index.min(), "->", df.index.max())
df.head()

(52608, 7)
2023-09-02 00:00:00+00:00 -> 2026-09-01 23:30:00+00:00

,open,high,low,close,volume,quote_volume,trade_count
bar_open_time_utc,,,,,,,
2023-09-02 00:00:00+00:00,25805.04,25834.00,25790.34,25832.72,267.87778,6.913767e+06,10100
2023-09-02 00:30:00+00:00,25832.73,25840.00,25781.40,25789.12,293.94001,7.586668e+06,10226
2023-09-02 01:00:00+00:00,25789.12,25814.00,25773.95,25799.57,287.33803,7.411593e+06,10529
2023-09-02 01:30:00+00:00,25799.58,25815.55,25773.67,25773.68,217.45912,5.608911e+06,9365
2023-09-02 02:00:00+00:00,25773.68,25795.69,25766.28,25795.69,231.76478,5.974187e+06,9430

In [35]:
feat

,ret_lag_1,ret_lag_2,ret_lag_3,ret_lag_6,ret_lag_12,ret_lag_24,ret_lag_48,ret_lag_96,ret_mean_6,ret_std_6,ret_skew_6,ret_mean_12,ret_std_12,ret_skew_12,ret_mean_24,ret_std_24,ret_skew_24,ret_mean_48,ret_std_48,ret_skew_48,ret_mean_96,ret_std_96,ret_skew_96,ret_mean_192,ret_std_192,...,bb_width_50,atr_14,atr_28,stoch_k_14,stoch_d_14,body,upper_wick,lower_wick,hl_range,vol_ratio_20,vol_chg_1,vol_z_20,dollar_vol_ratio_20,trade_count_z_20,roc_3,roc_6,roc_12,roc_24,winrate_10,winrate_20,winrate_50,hour_sin,hour_cos,dow_sin,dow_cos
bar_open_time_utc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2023-09-02 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.001690,0.001690,NaN,NaN,0.001073,0.000050,5.696562e-04,0.001690,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000,-0.974928,-0.222521
2023-09-02 00:30:00+00:00,-0.001689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.001734,0.001714,NaN,NaN,-0.001688,0.000281,2.988457e-04,0.002272,NaN,0.092845,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.130526,0.991445,-0.974928,-0.222521
2023-09-02 01:00:00+00:00,0.000405,-0.001284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.001721,0.001707,NaN,NaN,0.000405,0.000560,5.882326e-04,0.001552,NaN,-0.022716,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.258819,0.965926,-0.974928,-0.222521
2023-09-02 01:30:00+00:00,-0.001004,-0.000599,-0.002288,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.001715,0.001706,NaN,NaN,-0.001004,0.000619,3.876032e-07,0.001625,NaN,-0.278648,NaN,NaN,NaN,-0.002285,NaN,NaN,NaN,NaN,NaN,NaN,0.382683,0.923880,-0.974928,-0.222521
2023-09-02 02:00:00+00:00,0.000854,-0.000150,0.000255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.001673,0.001684,NaN,NaN,0.000854,0.000000,2.871146e-04,0.001140,NaN,0.063712,NaN,NaN,NaN,0.000255,NaN,NaN,NaN,NaN,NaN,NaN,0.500000,0.866025,-0.974928,-0.222521
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-09-01 21:30:00+00:00,0.000293,-0.003066,-0.002441,0.000744,-0.009125,-0.009072,-0.022450,-0.018500,0.000124,0.002034,-0.873599,-0.000760,0.002104,-0.087242,-0.000378,0.001946,-0.364258,-0.000468,0.002426,-0.966958,-0.000193,0.002647,-0.547736,-0.000010,0.002138,...,0.029681,0.004549,0.004311,45.226297,44.967814,0.000293,0.000795,1.989540e-03,0.003077,0.384387,-0.753742,-1.016392,0.382361,-0.820486,-0.002438,0.000744,-0.009083,-0.009031,0.5,0.45,0.48,-0.608761,0.793353,0.781831,0.623490
2026-09-01 22:00:00+00:00,-0.001806,-0.001513,-0.004873,-0.003761,-0.007125,-0.012044,-0.021690,-0.016856,-0.000627,0.001696,-0.848688,-0.000594,0.001912,-0.008095,-0.000502,0.001938,-0.202315,-0.000452,0.002415,-0.990629,-0.000176,0.002631,-0.559828,-0.000034,0.002133,...,0.030082,0.004454,0.004276,38.717340,40.766974,-0.001804,0.001304,0.000000e+00,0.003114,0.427345,0.099029,-0.929747,0.425506,-1.088347,-0.004861,-0.003754,-0.007100,-0.011972,0.5,0.45,0.46,-0.500000,0.866025,0.781831,0.623490
2026-09-01 22:30:00+00:00,0.002618,0.000812,0.001105,-0.000491,-0.004158,-0.009731,-0.016927,-0.014747,-0.000082,0.002151,-0.556076,-0.000347,0.002126,-0.050814,-0.000405,0.002035,-0.161885,-0.000353,0.002441,-1.034308,-0.000154,0.002646,-0.563622,-0.000033,0.002134,...,0.030022,0.004434,0.004267,54.885604,46.276414,0.002621,0.001168,5.450747e-04,0.004322,0.557348,0.252168,-0.701089,0.555068,-1.059710,0.001106,-0.000491,-0.004150,-0.009684,0.6,0.45,0.46,-0.382683,0.923880,0.781831,0.623490
2026-09-01 23:00:00+00:00,0.001588,0.004206,0.002400,-0.000041,-0.001512,-0.007880,-0.015179,-0.003627,-0.000007,0.002209,-0.587187,-0.000126,0.002182,-0.332400,-0.000328,0.002075,-0.232317,-0.000316,0.002457,-1.049807,-0.000038,0.002468,-0.244596,-0.000019,0.002136,...,0.029996,0.004276,0.004190,75.068779,56.223908,0.001589,0.000000,7.249526e-04,0.002311,0.354026,-0.508757,-0.954567,0.353166,-1.139766,0.002403,-0.000041,-0.001510,-0.007849,0.7,0.50,0.48,-0.258819,0.965926,0.781831,0.623490
2026-09-01 23:30:00+00:00,0.000545,0.002133,0.004750,-0.000122,0.002239,-0.008486,-0.014643,-0.003133,-0.000020,0.002205,-0.565487,0.000187,0.001958,-0.611038,-0.000354,0.002060,-0.211293,-0.000305,0.002460,-1.059621,-0.000033,0.002469,-0.250636,-0.000027,0.002131,...,0.030052,0.004202,0.004156,78.308716,69.421033,0.000545,0.002573,1.658983e-04,0.003282,0.783134,0.698778,-0.342805,0.783887,-0.780450,0.004762,-0.000122,0.002242,-0.008450,0.7,0.50,0.50,-0.130526,0.991445,0.781831,0.623490

## 2. Feature engineering

Identical feature set to the 1-bar-ahead notebook: price returns at multiple
lags, rolling return moments, moving-average deviations, MACD, RSI,
Bollinger Bands, ATR, stochastic oscillator, candle shape, volume/trade-count
anomalies, momentum (ROC), rolling win-rate, and cyclical time-of-day /
day-of-week encodings.

In [ ]:
o, h, l, c, v = df["open"], df["high"], df["low"], df["close"], df["volume"]
qv = df["quote_volume"]
tc = df["trade_count"]

feat = pd.DataFrame(index=df.index)
ret1 = np.log(c / c.shift(1))

# --- lagged log returns ---
for lag in [1, 2, 3, 6, 12, 24, 48, 96]:
    feat[f"ret_lag_{lag}"] = np.log(c / c.shift(lag))

# --- rolling return moments ---
for w in [6, 12, 24, 48, 96, 192]:
    feat[f"ret_mean_{w}"] = ret1.rolling(w).mean()
    feat[f"ret_std_{w}"] = ret1.rolling(w).std()
    feat[f"ret_skew_{w}"] = ret1.rolling(w).skew()

# --- moving-average deviation ---
for w in [5, 10, 20, 50, 100, 200]:
    sma = c.rolling(w).mean()
    ema = c.ewm(span=w, adjust=False).mean()
    feat[f"close_over_sma_{w}"] = c / sma - 1
    feat[f"close_over_ema_{w}"] = c / ema - 1

# --- MACD ---
ema12 = c.ewm(span=12, adjust=False).mean()
ema26 = c.ewm(span=26, adjust=False).mean()
macd = ema12 - ema26
macd_signal = macd.ewm(span=9, adjust=False).mean()
feat["macd"] = macd / c
feat["macd_signal"] = macd_signal / c
feat["macd_hist"] = (macd - macd_signal) / c


def rsi(series, w=14):
    delta = series.diff()
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)
    avg_gain = gain.ewm(alpha=1 / w, adjust=False).mean()
    avg_loss = loss.ewm(alpha=1 / w, adjust=False).mean()
    rs = avg_gain / avg_loss.replace(0, np.nan)
    return 100 - (100 / (1 + rs))


for w in [7, 14, 21]:
    feat[f"rsi_{w}"] = rsi(c, w)

# --- Bollinger Bands ---
for w in [20, 50]:
    sma = c.rolling(w).mean()
    std = c.rolling(w).std()
    upper, lower = sma + 2 * std, sma - 2 * std
    feat[f"bb_pctb_{w}"] = (c - lower) / (upper - lower)
    feat[f"bb_width_{w}"] = (upper - lower) / sma

# --- ATR ---
prev_close = c.shift(1)
tr = pd.concat([h - l, (h - prev_close).abs(), (l - prev_close).abs()], axis=1).max(axis=1)
for w in [14, 28]:
    atr = tr.ewm(alpha=1 / w, adjust=False).mean()
    feat[f"atr_{w}"] = atr / c

# --- stochastic oscillator ---
for w in [14]:
    lowest, highest = l.rolling(w).min(), h.rolling(w).max()
    k = 100 * (c - lowest) / (highest - lowest)
    feat[f"stoch_k_{w}"] = k
    feat[f"stoch_d_{w}"] = k.rolling(3).mean()

# --- candle shape ---
feat["body"] = (c - o) / o
feat["upper_wick"] = (h - np.maximum(o, c)) / o
feat["lower_wick"] = (np.minimum(o, c) - l) / o
feat["hl_range"] = (h - l) / c

# --- volume / activity anomalies ---
vol_ma = v.rolling(20).mean()
feat["vol_ratio_20"] = v / vol_ma
feat["vol_chg_1"] = np.log(v.replace(0, np.nan) / v.shift(1).replace(0, np.nan))
feat["vol_z_20"] = (v - vol_ma) / v.rolling(20).std()
feat["dollar_vol_ratio_20"] = qv / qv.rolling(20).mean()
feat["trade_count_z_20"] = (tc - tc.rolling(20).mean()) / tc.rolling(20).std()

# --- pct change ---
for w in [3, 6, 12, 24]:
    feat[f"roc_{w}"] = c.pct_change(w)

# --- rolling up-rate ---
up_bar = (c > o).astype(float)
for w in [10, 20, 50]:
    feat[f"uprate_{w}"] = up_bar.rolling(w).mean()

# --- cyclical time encodings ---
hour = df.index.hour + df.index.minute / 60
feat["hour_sin"] = np.sin(2 * np.pi * hour / 24)
feat["hour_cos"] = np.cos(2 * np.pi * hour / 24)
dow = df.index.dayofweek
feat["dow_sin"] = np.sin(2 * np.pi * dow / 7)
feat["dow_cos"] = np.cos(2 * np.pi * dow / 7)

print("num features:", feat.shape[1])
feat.tail()

num features: 72

,ret_lag_1,ret_lag_2,ret_lag_3,ret_lag_6,ret_lag_12,ret_lag_24,ret_lag_48,ret_lag_96,ret_mean_6,ret_std_6,...,roc_6,roc_12,roc_24,winrate_10,winrate_20,winrate_50,hour_sin,hour_cos,dow_sin,dow_cos
bar_open_time_utc,,,,,,,,,,,,,,,,,,,,,
2026-09-01 21:30:00+00:00,0.000293,-0.003066,-0.002441,0.000744,-0.009125,-0.009072,-0.022450,-0.018500,0.000124,0.002034,...,0.000744,-0.009083,-0.009031,0.5,0.45,0.48,-0.608761,0.793353,0.781831,0.62349
2026-09-01 22:00:00+00:00,-0.001806,-0.001513,-0.004873,-0.003761,-0.007125,-0.012044,-0.021690,-0.016856,-0.000627,0.001696,...,-0.003754,-0.007100,-0.011972,0.5,0.45,0.46,-0.500000,0.866025,0.781831,0.62349
2026-09-01 22:30:00+00:00,0.002618,0.000812,0.001105,-0.000491,-0.004158,-0.009731,-0.016927,-0.014747,-0.000082,0.002151,...,-0.000491,-0.004150,-0.009684,0.6,0.45,0.46,-0.382683,0.923880,0.781831,0.62349
2026-09-01 23:00:00+00:00,0.001588,0.004206,0.002400,-0.000041,-0.001512,-0.007880,-0.015179,-0.003627,-0.000007,0.002209,...,-0.000041,-0.001510,-0.007849,0.7,0.50,0.48,-0.258819,0.965926,0.781831,0.62349
2026-09-01 23:30:00+00:00,0.000545,0.002133,0.004750,-0.000122,0.002239,-0.008486,-0.014643,-0.003133,-0.000020,0.002205,...,-0.000122,0.002242,-0.008450,0.7,0.50,0.50,-0.130526,0.991445,0.781831,0.62349

In [36]:
feat

,ret_lag_1,ret_lag_2,ret_lag_3,ret_lag_6,ret_lag_12,ret_lag_24,ret_lag_48,ret_lag_96,ret_mean_6,ret_std_6,ret_skew_6,ret_mean_12,ret_std_12,ret_skew_12,ret_mean_24,ret_std_24,ret_skew_24,ret_mean_48,ret_std_48,ret_skew_48,ret_mean_96,ret_std_96,ret_skew_96,ret_mean_192,ret_std_192,...,bb_width_50,atr_14,atr_28,stoch_k_14,stoch_d_14,body,upper_wick,lower_wick,hl_range,vol_ratio_20,vol_chg_1,vol_z_20,dollar_vol_ratio_20,trade_count_z_20,roc_3,roc_6,roc_12,roc_24,winrate_10,winrate_20,winrate_50,hour_sin,hour_cos,dow_sin,dow_cos
bar_open_time_utc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2023-09-02 00:00:00+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.001690,0.001690,NaN,NaN,0.001073,0.000050,5.696562e-04,0.001690,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000,-0.974928,-0.222521
2023-09-02 00:30:00+00:00,-0.001689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.001734,0.001714,NaN,NaN,-0.001688,0.000281,2.988457e-04,0.002272,NaN,0.092845,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.130526,0.991445,-0.974928,-0.222521
2023-09-02 01:00:00+00:00,0.000405,-0.001284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.001721,0.001707,NaN,NaN,0.000405,0.000560,5.882326e-04,0.001552,NaN,-0.022716,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.258819,0.965926,-0.974928,-0.222521
2023-09-02 01:30:00+00:00,-0.001004,-0.000599,-0.002288,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.001715,0.001706,NaN,NaN,-0.001004,0.000619,3.876032e-07,0.001625,NaN,-0.278648,NaN,NaN,NaN,-0.002285,NaN,NaN,NaN,NaN,NaN,NaN,0.382683,0.923880,-0.974928,-0.222521
2023-09-02 02:00:00+00:00,0.000854,-0.000150,0.000255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.001673,0.001684,NaN,NaN,0.000854,0.000000,2.871146e-04,0.001140,NaN,0.063712,NaN,NaN,NaN,0.000255,NaN,NaN,NaN,NaN,NaN,NaN,0.500000,0.866025,-0.974928,-0.222521
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-09-01 21:30:00+00:00,0.000293,-0.003066,-0.002441,0.000744,-0.009125,-0.009072,-0.022450,-0.018500,0.000124,0.002034,-0.873599,-0.000760,0.002104,-0.087242,-0.000378,0.001946,-0.364258,-0.000468,0.002426,-0.966958,-0.000193,0.002647,-0.547736,-0.000010,0.002138,...,0.029681,0.004549,0.004311,45.226297,44.967814,0.000293,0.000795,1.989540e-03,0.003077,0.384387,-0.753742,-1.016392,0.382361,-0.820486,-0.002438,0.000744,-0.009083,-0.009031,0.5,0.45,0.48,-0.608761,0.793353,0.781831,0.623490
2026-09-01 22:00:00+00:00,-0.001806,-0.001513,-0.004873,-0.003761,-0.007125,-0.012044,-0.021690,-0.016856,-0.000627,0.001696,-0.848688,-0.000594,0.001912,-0.008095,-0.000502,0.001938,-0.202315,-0.000452,0.002415,-0.990629,-0.000176,0.002631,-0.559828,-0.000034,0.002133,...,0.030082,0.004454,0.004276,38.717340,40.766974,-0.001804,0.001304,0.000000e+00,0.003114,0.427345,0.099029,-0.929747,0.425506,-1.088347,-0.004861,-0.003754,-0.007100,-0.011972,0.5,0.45,0.46,-0.500000,0.866025,0.781831,0.623490
2026-09-01 22:30:00+00:00,0.002618,0.000812,0.001105,-0.000491,-0.004158,-0.009731,-0.016927,-0.014747,-0.000082,0.002151,-0.556076,-0.000347,0.002126,-0.050814,-0.000405,0.002035,-0.161885,-0.000353,0.002441,-1.034308,-0.000154,0.002646,-0.563622,-0.000033,0.002134,...,0.030022,0.004434,0.004267,54.885604,46.276414,0.002621,0.001168,5.450747e-04,0.004322,0.557348,0.252168,-0.701089,0.555068,-1.059710,0.001106,-0.000491,-0.004150,-0.009684,0.6,0.45,0.46,-0.382683,0.923880,0.781831,0.623490
2026-09-01 23:00:00+00:00,0.001588,0.004206,0.002400,-0.000041,-0.001512,-0.007880,-0.015179,-0.003627,-0.000007,0.002209,-0.587187,-0.000126,0.002182,-0.332400,-0.000328,0.002075,-0.232317,-0.000316,0.002457,-1.049807,-0.000038,0.002468,-0.244596,-0.000019,0.002136,...,0.029996,0.004276,0.004190,75.068779,56.223908,0.001589,0.000000,7.249526e-04,0.002311,0.354026,-0.508757,-0.954567,0.353166,-1.139766,0.002403,-0.000041,-0.001510,-0.007849,0.7,0.50,0.48,-0.258819,0.965926,0.781831,0.623490
2026-09-01 23:30:00+00:00,0.000545,0.002133,0.004750,-0.000122,0.002239,-0.008486,-0.014643,-0.003133,-0.000020,0.002205,-0.565487,0.000187,0.001958,-0.611038,-0.000354,0.002060,-0.211293,-0.000305,0.002460,-1.059621,-0.000033,0.002469,-0.250636,-0.000027,0.002131,...,0.030052,0.004202,0.004156,78.308716,69.421033,0.000545,0.002573,1.658983e-04,0.003282,0.783134,0.698778,-0.342805,0.783887,-0.780450,0.004762,-0.000122,0.002242,-0.008450,0.7,0.50,0.50,-0.130526,0.991445,0.781831,0.623490

## 3. Target and leakage-safe alignment

In [ ]:
def create_dataset(feat, o, horizon=1):
    target_pct = (o.shift(-horizon) - o) / o * 100   # % move from open[t] to open[t+HORIZON]
    # target_up = (target_pct > threshold).astype(int)

    # shift the ENTIRE feature matrix forward by 1 bar so that predicting target[t]
    # only ever uses information available through bar t-1 (the target window
    # [t, t+HORIZON] still starts with bar t's own price action)
    X_all = feat.shift(1)

    dataset = pd.concat([X_all, target_pct.rename("y_reg")], axis=1)
    dataset = dataset.dropna()

    feature_cols = [col for col in dataset.columns if col not in ("y_reg")]
    print("rows:", len(dataset), " features:", len(feature_cols))
    return dataset

In [40]:
dataset = create_dataset(feat, o, horizon=1)
dataset.to_csv("./data/processed_dataset_target_lag1.csv", index=True)

rows: 52407  features: 72

In [33]:
dataset = create_dataset(feat, o, horizon=6)
dataset.to_csv("./data/processed_dataset_target_lag6.csv", index=True)

rows: 52402  features: 72

In [41]:
dataset = create_dataset(feat, o, horizon=12)
dataset.to_csv("./data/processed_dataset_target_lag12.csv", index=True)

rows: 52396  features: 72

In [42]:
dataset

,ret_lag_1,ret_lag_2,ret_lag_3,ret_lag_6,ret_lag_12,ret_lag_24,ret_lag_48,ret_lag_96,ret_mean_6,ret_std_6,ret_skew_6,ret_mean_12,ret_std_12,ret_skew_12,ret_mean_24,ret_std_24,ret_skew_24,ret_mean_48,ret_std_48,ret_skew_48,ret_mean_96,ret_std_96,ret_skew_96,ret_mean_192,ret_std_192,...,atr_14,atr_28,stoch_k_14,stoch_d_14,body,upper_wick,lower_wick,hl_range,vol_ratio_20,vol_chg_1,vol_z_20,dollar_vol_ratio_20,trade_count_z_20,roc_3,roc_6,roc_12,roc_24,winrate_10,winrate_20,winrate_50,hour_sin,hour_cos,dow_sin,dow_cos,y_reg
bar_open_time_utc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2023-09-06 04:00:00+00:00,-0.000872,-0.002587,-0.000928,-0.000797,0.001857,0.000911,0.003513,-0.007908,-0.000133,0.001272,0.294524,0.000155,0.000937,-0.584602,0.000038,0.000993,-0.283961,0.000073,0.001231,0.387824,-0.000082,0.001282,0.188106,-0.000003,0.001184,...,0.001921,0.002181,44.535848,68.636078,-0.000872,0.000105,2.065463e-04,0.001185,0.814265,-0.384675,-0.632644,0.815047,-0.693724,-0.000928,-0.000797,0.001859,0.000912,0.7,0.60,0.58,0.793353,0.608761,0.974928,-0.222521,-0.114068
2023-09-06 04:30:00+00:00,-0.000182,-0.001054,-0.002769,-0.001141,0.000718,-0.000083,0.003343,-0.008208,-0.000190,0.001264,0.500318,0.000060,0.000905,-0.350422,-0.000003,0.000980,-0.180944,0.000070,0.001231,0.396183,-0.000085,0.001282,0.195579,0.000002,0.001181,...,0.001840,0.002132,41.568057,50.924660,-0.000182,0.000225,3.769945e-04,0.000784,0.878030,0.062553,-0.410201,0.878412,-0.573330,-0.002765,-0.001140,0.000718,-0.000083,0.6,0.60,0.58,0.866025,0.500000,0.974928,-0.222521,-0.102529
2023-09-06 05:00:00+00:00,-0.000884,-0.001066,-0.001938,-0.001084,-0.000501,0.000069,0.002221,-0.008785,-0.000181,0.001257,0.487812,-0.000042,0.000939,-0.036187,0.000003,0.000973,-0.184364,0.000046,0.001239,0.437999,-0.000092,0.001284,0.206295,-0.000005,0.001182,...,0.001812,0.002108,19.479611,35.194505,-0.000884,0.000546,3.879250e-07,0.001432,0.768627,-0.139294,-0.763733,0.768675,-0.660928,-0.001936,-0.001084,-0.000501,0.000069,0.5,0.55,0.56,0.923880,0.382683,0.974928,-0.222521,-0.110540
2023-09-06 05:30:00+00:00,0.000111,-0.000773,-0.000955,-0.001883,-0.001085,0.000428,0.001413,-0.008525,-0.000314,0.001157,0.900231,-0.000090,0.000912,0.095787,0.000018,0.000972,-0.234611,0.000029,0.001232,0.480021,-0.000089,0.001284,0.199812,-0.000016,0.001172,...,0.001730,0.002056,6.845905,22.631191,0.000111,0.000338,2.092766e-04,0.000658,0.728981,-0.092719,-0.905344,0.728558,-0.240098,-0.000955,-0.001882,-0.001084,0.000428,0.5,0.60,0.58,0.965926,0.258819,0.974928,-0.222521,0.020343
2023-09-06 06:00:00+00:00,-0.000454,-0.000343,-0.001227,-0.003996,-0.001768,-0.000098,0.000514,-0.007271,-0.000666,0.000644,-0.653274,-0.000147,0.000912,0.309337,-0.000004,0.000976,-0.163147,0.000011,0.001233,0.524929,-0.000076,0.001274,0.195122,-0.000015,0.001171,...,0.001657,0.002009,4.924068,10.416528,-0.000455,0.000000,2.492404e-04,0.000704,0.768057,0.038178,-0.752242,0.767276,-0.291600,-0.001227,-0.003988,-0.001766,-0.000098,0.4,0.60,0.56,0.991445,0.130526,0.974928,-0.222521,-0.051541
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-09-01 15:30:00+00:00,-0.003830,-0.005033,-0.002601,-0.001601,-0.000797,-0.007786,-0.007596,-0.011777,-0.000267,0.002423,-0.212747,-0.000066,0.001769,-0.515562,-0.000324,0.002734,-1.650573,-0.000158,0.002382,-1.107785,-0.000123,0.002661,-0.596289,-0.000097,0.002425,...,0.004166,0.003963,39.300875,51.701379,-0.003822,0.000022,1.811483e-03,0.005677,1.073738,0.216929,0.149012,1.069908,0.319950,-0.002597,-0.001600,-0.000797,-0.007756,0.5,0.45,0.52,-0.707107,-0.707107,0.781831,0.623490,-0.873940
2026-09-01 16:00:00+00:00,0.000640,-0.003190,-0.004393,-0.001090,0.000052,-0.009706,-0.008452,-0.011542,-0.000182,0.002449,-0.349021,0.000004,0.001780,-0.642598,-0.000404,0.002674,-1.724792,-0.000176,0.002373,-1.104240,-0.000120,0.002662,-0.598531,-0.000027,0.002246,...,0.004134,0.003953,44.754923,47.123834,0.000640,0.002375,7.382891e-04,0.003751,0.593839,-0.609680,-0.792920,0.592798,-0.724575,-0.004384,-0.001089,0.000052,-0.009659,0.5,0.45,0.52,-0.793353,-0.608761,0.781831,0.623490,-0.908314
2026-09-01 16:30:00+00:00,-0.003805,-0.003165,-0.006995,-0.003411,-0.004918,-0.015422,-0.013107,-0.018136,-0.000569,0.002847,-0.195852,-0.000410,0.002044,-0.410121,-0.000643,0.002713,-1.486161,-0.000273,0.002425,-0.985901,-0.000189,0.002671,-0.555675,0.000006,0.002137,...,0.004321,0.004060,16.226987,33.427595,-0.003798,0.000731,1.990912e-03,0.006544,1.038205,0.573029,0.076104,1.033061,0.160049,-0.006970,-0.003406,-0.004906,-0.015304,0.5,0.45,0.52,-0.866025,-0.500000,0.781831,0.623490,-0.709982
2026-09-01 17:00:00+00:00,-0.000349,-0.004155,-0.003515,-0.006115,-0.005573,-0.014472,-0.013359,-0.022200,-0.001019,0.002482,0.042674,-0.000464,0.002032,-0.325566,-0.000603,0.002710,-1.538347,-0.000278,0.002425,-0.979263,-0.000231,0.002641,-0.560754,-0.000013,0.002124,...,0.004321,0.004070,25.136528,28.706146,-0.000349,0.000372,3.581536e-03,0.004304,0.996846,-0.021361,-0.006506,0.990700,0.032539,-0.003508,-0.006097,-0.005558,-0.014367,0.4,0.45,0.50,-0.923880,-0.382683,0.781831,0.623490,-0.414957
2026-09-01 17:30:00+00:00,-0.001058,-0.001408,-0.005213,-0.009607,-0.006368,-0.018904,-0.013077,-0.018238,-0.001601,0.001837,-0.403663,-0.000531,0.002038,-0.208505,-0.000788,0.002575,-1.733484,-0.000272,0.002422,-0.988488,-0.000190,0.002595,-0.572003,-0.000029,0.002121,...,0.004234,0.004038,17.714286,19.692600,-0.001058,0.000722,1.251224e-03,0.003034,0.604798,-0.489386,-0.843346,0.601577,-0.777880,-0.005199,-0.009561,-0.006348,-0.018727,0.4,0.40,0.48,-0.965926,-0.258819,0.781831,0.623490,-0.151070